<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="c"	uri="http://java.sun.com/jsp/jstl/core" %>
<content tag="main">
<div>
<!-- 	<img style="width: 100%;" src="/resources/img/Corinthians2_9.jpg" /> -->
	<div> <c:out value="${memberName}" />님의 대여현황</div>
	<table>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납예정일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
	</table>
	<div style="padding-top: 5px;"> 대여내역 </div>
	<table>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
		<tr>
			<td>도서명</td>
			<td>대여일</td>
			<td>반납일</td>
		</tr>
	</table>
</div>
</content>